### PR TITLE
Add Magnetic Scrolls interpreter from upstream

### PR DESCRIPTION
**Pull request by cibersheep**
- Cloned from https://github.com/DavidKinder/Magnetic/
- Removed other implementations
- Renamed main directory to lowcase

### CODE REVIEW

**Comment by cspiegel** [comment]
This looks good, I think, but just one request: please convert all line endings from DOS to Unix in upstream.  That does mean there will be (superficial) differences in our upstream vs the actual upstream, but I'd like the whole project to be uniform on line endings: I've converted the other repos to Unix-style endings, so it'd be in line with what already exists.

Apart from that, I think it's ready to merge.  In fact, it's probably _better_ than what I've been doing, in that you've got a record of which files you removed from upstream, whereas I just removed them before committing.  I like the paper trail.

**Comment by cibersheep** [comment]
> [...]just one request: please convert all line endings from DOS to Unix in upstream.

Oh, I didn't think of that. ~~Is there a bulk way of doing it? Or the old 'open and save' method :)~~ Ok, I found a couple of methods :) 

> [...] you've got a record of which files you removed from upstream

Good, thanks :) I thought it might be good if we need to repeat the process (it can be messy, specially after months of tests... do you want to see my test drive?)

**Comment by cspiegel** [comment]
> Good, thanks :) I thought it might be good if we need to repeat the process (it can be messy, specially after months of tests... do you want to see my test drive?)

My thoughts exactly: by now there's no way I remember what I removed (or why) from the other upstreams.  When/if I update them (depending on upstream activity), I'll do it your way and create a new paper trail, at least.  At this point rewriting the history would be impossibly messy.

I'd love to see anything you've got!

**Comment by cibersheep** [comment]
I thought this interpreter was on of the easy ones, I hesitate between some changes though. I trusted the date of modifications.
Maybe it would be useful to add a log of the building.
Also, I don't know how to test for known issues. I guess playing :)

**Pull request merged**
